---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nhs
  labels:
    gitops.tier.layer: infra
spec:
  sourceRepos: ["https://github.com/ducmk254/pvc-ocp-argocd.git"] # Populated by kustomize patches in 1-infra/kustomization.yaml
  scopedRepos: ["https://github.com/ducmk254/pvc-ocp-argocd.git"]
  destinations: # list of namespace on nhs project
  - namespace: qlts
    server: https://kubernetes.default.svc
  - namespace: test
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  # TODO: SCC needs to be moved to 1-infra, here for now pipeline sa for buildah
  - group: "security.openshift.io"
    kind: SecurityContextConstraints
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRole
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRoleBinding
  - group: "route.openshift.io"
    kind: routes
  - group: "monitoring.coreos.com"
    kind: servicemonitors
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to my-project
    policies:
    - p, proj:my-project:read-only, applications, get, my-project/*, allow
    groups:
    - argocd-admins
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: infra
#   annotations:
#     argocd.argoproj.io/sync-wave: "100"
#   labels:
#     gitops.tier.layer: gitops
# spec:
#   destination:
#     namespace: openshift-gitops
#     server: https://kubernetes.default.svc
#   project: infra
#   source: # repoURL  and targetRevision populated by kustomize patches in 1-infra/kustomization.yaml
#     path: 0-bootstrap/others/2-isolated-cluster/dr-m3-ocp-dev02/1-infra
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
